import {
  abcdef,
  abcdefMergeStyles,
  abyss,
  abyssMergeStyles,
  androidStudio,
  androidStudioMergeStyles,
  andromeda,
  andromedaMergeStyles,
  applyMergeRevertStyles,
  basicDark,
  basicDarkMergeStyles,
  basicLight,
  basicLightMergeStyles,
  catppuccinMocha,
  catppuccinMochaMergeStyles,
  cobalt2,
  cobalt2MergeStyles,
  forest,
  forestMergeStyles,
  githubDark,
  githubDarkMergeStyles,
  githubLight,
  githubLightMergeStyles,
  gruvboxDark,
  gruvboxDarkMergeStyles,
  gruvboxLight,
  gruvboxLightMergeStyles,
  highContrastDark,
  highContrastDarkMergeStyles,
  highContrastLight,
  highContrastLightMergeStyles,
  materialDark,
  materialDarkMergeStyles,
  materialLight,
  materialLightMergeStyles,
  materialOcean,
  materialOceanMergeStyles,
  monokai,
  monokaiMergeStyles,
  nord,
  nordMergeStyles,
  palenight,
  palenightMergeStyles,
  solarizedDark,
  solarizedDarkMergeStyles,
  solarizedLight,
  solarizedLightMergeStyles,
  synthwave84,
  synthwave84MergeStyles,
  tokyoNightDay,
  tokyoNightDayMergeStyles,
  tokyoNightStorm,
  tokyoNightStormMergeStyles,
  volcano,
  volcanoMergeStyles,
  vsCodeDark,
  vsCodeDarkMergeStyles,
  vsCodeLight,
  vsCodeLightMergeStyles,
} from '@fsegurai/codemirror-theme-bundle';

/**
 * List of CodeMirror themes
 */
const CodeMirrorThemes = [
  {
    viewValue: 'abcdef',
    value: abcdef,
    mergeStyles: abcdefMergeStyles,
  },
  {
    viewValue: 'abyss',
    value: abyss,
    mergeStyles: abyssMergeStyles,
  },
  {
    viewValue: 'android studio',
    value: androidStudio,
    mergeStyles: androidStudioMergeStyles,
  },
  {
    viewValue: 'andromeda',
    value: andromeda,
    mergeStyles: andromedaMergeStyles,
  },
  {
    viewValue: 'basic light',
    value: basicLight,
    mergeStyles: basicLightMergeStyles,
  },
  {
    viewValue: 'basic dark',
    value: basicDark,
    mergeStyles: basicDarkMergeStyles,
  },
  {
    viewValue: 'catppuccin mocha',
    value: catppuccinMocha,
    mergeStyles: catppuccinMochaMergeStyles,
  },
  {
    viewValue: 'cobalt2',
    value: cobalt2,
    mergeStyles: cobalt2MergeStyles,
  },
  {
    viewValue: 'forest',
    value: forest,
    mergeStyles: forestMergeStyles,
  },
  {
    viewValue: 'github light',
    value: githubLight,
    mergeStyles: githubLightMergeStyles,
  },
  {
    viewValue: 'github dark',
    value: githubDark,
    mergeStyles: githubDarkMergeStyles,
  },
  {
    viewValue: 'gruvbox light',
    value: gruvboxLight,
    mergeStyles: gruvboxLightMergeStyles,
  },
  {
    viewValue: 'gruvbox dark',
    value: gruvboxDark,
    mergeStyles: gruvboxDarkMergeStyles,
  },
  {
    viewValue: 'high contrast light',
    value: highContrastLight,
    mergeStyles: highContrastLightMergeStyles,
  },
  {
    viewValue: 'high contrast dark',
    value: highContrastDark,
    mergeStyles: highContrastDarkMergeStyles,
  },
  {
    viewValue: 'material light',
    value: materialLight,
    mergeStyles: materialLightMergeStyles,
  },
  {
    viewValue: 'material dark',
    value: materialDark,
    mergeStyles: materialDarkMergeStyles,
  },
  {
    viewValue: 'material ocean',
    value: materialOcean,
    mergeStyles: materialOceanMergeStyles,
  },
  {
    viewValue: 'monokai',
    value: monokai,
    mergeStyles: monokaiMergeStyles,
  },
  {
    viewValue: 'nord',
    value: nord,
    mergeStyles: nordMergeStyles,
  },
  {
    viewValue: 'palenight',
    value: palenight,
    mergeStyles: palenightMergeStyles,
  },
  {
    viewValue: 'solarized light',
    value: solarizedLight,
    mergeStyles: solarizedLightMergeStyles,
  },
  {
    viewValue: 'solarized dark',
    value: solarizedDark,
    mergeStyles: solarizedDarkMergeStyles,
  },
  {
    viewValue: 'synthwave 84',
    value: synthwave84,
    mergeStyles: synthwave84MergeStyles,
  },
  {
    viewValue: 'tokyo night day',
    value: tokyoNightDay,
    mergeStyles: tokyoNightDayMergeStyles,
  },
  {
    viewValue: 'tokyo night storm',
    value: tokyoNightStorm,
    mergeStyles: tokyoNightStormMergeStyles,
  },
  {
    viewValue: 'volcano',
    value: volcano,
    mergeStyles: volcanoMergeStyles,
  },
  {
    viewValue: 'vsCode light',
    value: vsCodeLight,
    mergeStyles: vsCodeLightMergeStyles,
  },
  {
    viewValue: 'vsCode dark',
    value: vsCodeDark,
    mergeStyles: vsCodeDarkMergeStyles,
  },
];

export { applyMergeRevertStyles, CodeMirrorThemes };
